
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
# https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/
metadata:
  namespace: argocd
  name: my-infra
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  # https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Generators-Git/
  - git:
      repoURL: https://github.com/kristoferlundgren/my-infra
      revision: release/staging
      requeueAfterSeconds: 60 # Pull repo every x seconds
      files:
      # TODO: Enable improved globbing
      # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git-File-Globbing/#enabling-the-new-globbing
      - path: AppSet/app.yaml # Deploy the AppSet itself, to manage the rest of the apps.
      - path: Apps/*/app.yaml # Deploy all apps
      - path: Apps/app.template/* # Exclude app.template
        exclude: true
      # - path: Apps/*/*.app.yaml # Future: Support multiple app.yaml files per app.
      values:
        applicationProject: infra
        clusterURL: https://kubernetes.default.svc
        repoURL: https://github.com/kristoferlundgren/my-infra
        targetRevision: release/staging
  ignoreApplicationDifferences:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
    - jsonPointers:
        - /spec/syncPolicy
  syncPolicy:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#managed-applications-modification-policies
    applicationsSync: create-only # create-only, create-update, create-delete, sync (default)
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true,IgnoreExtraneous
        argocd.argoproj.io/sync-wave: "-500" # Created first, destroyed last
      finalizers:
        # https://argo-cd.readthedocs.io/en/latest/user-guide/app_deletion/#about-the-deletion-finalizer
        - resources-finalizer.argocd.argoproj.io
      name: 'my-infra.{{.path.basenameNormalized}}'
    spec:
      project: '{{.values.applicationProject}}'
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      destination:
        namespace: '{{.path.basenameNormalized}}'
        server: '{{.values.clusterURL}}'
      source:
        repoURL: '{{.values.repoURL}}'
        targetRevision: '{{.values.targetRevision}}'
        path: '{{.path.path}}'
        helm:
          releaseName: '{{.path.basenameNormalized}}'
          valueFiles:
            - 'values.yaml'
