spec:
  source:
    chart: oauth2-proxy
    repoURL: https://oauth2-proxy.github.io/manifests
    # https://artifacthub.io/packages/helm/oauth2-proxy/oauth2-proxy
    targetRevision: 10.6.0
    #helm:
    #  valuesObject:
