# Kyverno, policy-reporter
# https://kyverno.github.io/policy-reporter-docs/
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  source:
    chart: policy-reporter
    repoURL: https://kyverno.github.io/policy-reporter
    # https://artifacthub.io/packages/helm/policy-reporter/policy-reporter
    targetRevision: 3.7.4
