ui:
  enabled: true
  ingress:
    enabled: true
    className: traefik
    hosts:
      - host: policy-reporter-ui.k8s.orb.local
        paths:
          - path: "/"
            pathType: ImplementationSpecific
      - host: policy-reporter-ui.localhost
        paths:
          - path: "/"
            pathType: ImplementationSpecific
plugin:
  kyverno:
    enabled: true
    networkPolicy:
      enabled: true
monitoring:
  grafana:
    grafanaDashboard:
      enabled: true # Requires Grafana Operator
