spec:
  source:
    # https://docs.victoriametrics.com/helm/
    chart: victoria-metrics-operator
    repoURL: https://victoriametrics.github.io/helm-charts/
    # https://artifacthub.io/packages/helm/victoriametrics/victoria-metrics-operator
    targetRevision: 0.63.1
