deployment:
  replicas: 2
gateway:
  enabled: true
global:
  checkNewVersion: false
  sendAnonymousUsage: false
ingressClass:
  isDefaultClass: true
ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - web
  healthcheck:
    enabled: true
providers:
  kubernetesGateway:
    enabled: true
  kubernetesIngress:
    ingressClass: traefik
# Error: values don't meet the specifications of the schema(s) in the following chart(s): traefik: - at '/providers': additional properties 'kubernetesIngressNginx' not allowed
#   kubernetesIngressNginx:
#     enabled: true
#     publishService:
#       enabled: true
service:
  type: ClusterIP
