deployment:
  replicas: 2
gateway:
  enabled: true
global:
  checkNewVersion: false
  sendAnonymousUsage: false
ingressClass:
  isDefaultClass: true
ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - web
  healthcheck:
    enabled: true
providers:
  kubernetesGateway:
    enabled: true
  kubernetesIngress:
    ingressClass: traefik
service:
  spec:
    type: ClusterIP
