apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
# https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/
metadata:
  namespace: argocd
  name: projekt-deployments
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/kristoferlundgren/my-infra
      revision: release/staging
      requeueAfterSeconds: 60 # Pull repo every x seconds
      directories:
      - path: AppSet/self
      - path: AppSet/apps/*
      values:
        applicationNamespace: infra
        applicationProject: infra
        clusterURL: https://kubernetes.default.svc
        repoURL: https://github.com/kristoferlundgren/my-infra
        targetRevision: release/staging
  ignoreApplicationDifferences:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
    - jsonPointers:
        - /spec/syncPolicy
  syncPolicy:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#managed-applications-modification-policies
    applicationsSync: create-only # create-update, create-delete sync
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true,IgnoreExtraneous
        argocd.argoproj.io/sync-wave: "-500" # Created first, destroyed last
      finalizers:
        # https://argo-cd.readthedocs.io/en/latest/user-guide/app_deletion/#about-the-deletion-finalizer
        - resources-finalizer.argocd.argoproj.io
      name: 'my-infra.{{.path.basenameNormalized}}'
      namespace: {{ .Values.applicationNamespace }}
    spec:
      project: {{ .Values.applicationProject }}
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      destination:
        namespace: '{{.path.basenameNormalized}}'
        server: {{ .Values.clusterURL }}
      source:
        repoURL: {{ .Values.repoURL }}
        targetRevision: {{ .Values.targetRevision }}
        path: '{{.path.path}}'
        helm:
          releaseName: '{{.path.basenameNormalized}}'
          valueFiles: '{{.path.path}}'/values.yaml
