metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  source:
    chart: openbao
    repoURL: https://openbao.github.io/openbao-helm
    # https://artifacthub.io/packages/helm/openbao/openbao
    targetRevision: 0.28.3
