metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  source:
    chart: trivy-operator
    repoURL: https://aquasecurity.github.io/helm-charts/
    # https://artifacthub.io/packages/helm/trivy-operator/trivy-operator
    # https://aquasecurity.github.io/trivy-operator/latest/getting-started/installation/helm/
    targetRevision: 0.32.1
    helm:
      releaseName: trivy-operator
      #valuesObject:
