metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  source:
    chart: dex
    repoURL: https://charts.dexidp.io
    # https://artifacthub.io/packages/helm/dex/dex
    targetRevision: 0.24.1
