metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  source:
    chart: harbor
    repoURL: https://helm.goharbor.io
    # https://artifacthub.io/packages/helm/harbor/harbor
    targetRevision: 1.19.1
