apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: infra
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  project: infra
  destination:
    namespace: grafana-operator
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    chart: grafana-operator
    repoURL: oci://ghcr.io/grafana/helm-charts/grafana-operator
    targetRevision: v5.19.4
    helm:
      valuesObject:
