apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: infra
  annotations:
    # https://github.com/argoproj/argo-cd/issues/11143
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  project: infra
  destination:
    namespace: harbor
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: 1.15.0
    helm:
      valuesObject:
        expose:
          type: clusterIP
          tls:
            enabled: false
        core:
          replicas: 1 # HA>=2
        portal:
          replicas: 1
        jobservice:
          replicas: 1
        registry:
          replicas: 1
        metrics:
          enabled: true
