apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  finalizers:
    # https://argo-cd.readthedocs.io/en/latest/user-guide/app_deletion/#about-the-deletion-finalizer
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    namespace: kyverno
    server: {{ .Values.server }}
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - Force=true
      - Replace=true
      - ServerSideApply=true
  source:
    chart: kyverno-policies
    repoURL: https://kyverno.github.io/kyverno/
    # https://artifacthub.io/packages/helm/kyverno-policies-oci/kyverno-policies
    # https://kyverno.io/docs/installation/methods/#install-pod-security-policies-via-helm
    # https://kyverno.io/policies/pod-security/
    # https://kubernetes.io/docs/concepts/security/pod-security-standards/
    targetRevision: 3.7.1
    helm:
      releaseName: kyverno-policies # Override ArgoCD application name
      valuesObject:
        policyKind: ClusterPolicy
        policyType: ClusterPolicy # TODO: Change to "ValidatingPolicy" When Kyverno v1.18 is released (https://github.com/kyverno/kyverno/issues/15640)
        podSecurityStandard: restricted
        validationFailureAction: Audit # TODO: Change to Enforce
        validationFailureActionOverrides:
          all:
            - action: audit
              namespaces:
                - kube-system
        validationFailureActionByPolicy: # (`Audit`, `Enforce`)
            disallow-capabilities-strict: Audit
            disallow-privilege-escalation: Audit
            require-run-as-nonroot: Audit
            restrict-seccomp-strict: Audit
            disallow-host-process: Enforce
            disallow-privileged-containers: Enforce
        policyExclude:
        # Exclude "restricted" policies from selected namespaces to avoid breaking critical workloads.
          {{- range $policy := list
            "disallow-capabilities"
            "disallow-capabilities-strict"
            "disallow-host-namespaces"
            "disallow-host-path"
            "disallow-host-ports"
            "disallow-host-process"
            "disallow-privilege-escalation"
            "disallow-privileged-containers"
            "disallow-proc-mount"
            "disallow-selinux"
            "require-run-as-non-root-user"
            "require-run-as-nonroot"
            "restrict-apparmor-profiles"
            "restrict-seccomp"
            "restrict-seccomp-strict"
            "restrict-sysctls"
            "restrict-volume-types"
          }}
          {{ $policy }}:
            any:
              - resources:
                  kinds:
                    - DaemonSet
                    - Deployment
                    - Job
                    - Pod
                    - ReplicaSet
                    - StatefulSet
                    - Cronjob
                  namespaces:
                    - argocd
                    - cert-manager
                    - default
                    - devpod
                    - dex
                    - grafana-operator
                    - grafana-test
                    - harbor
                    - infra
                    - ingress-nginx
                    - kong
                    - kube-node-lease
                    - kube-prometheus-stack
                    - kube-public
                    - kube-system
                    - kyverno
                    - kyverno-policy-reporter
                    - litellm
                    - metallb
                    - multitool-a
                    - multitool-b
                    - my-apps
                    - open-webui
                    - openbao
                    - opentelemetry-collector
                    - opentelemetry-operator
                    - plantuml-server
                    - pomerium
                    - portkey
                    - reloader
                    - sealed-secrets
                    - traefik
                    - trivy-operator
                    - victorialogs
                    - victoriametrics-operator
          {{- end }}
