# wbitt/network-multitool:latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: multitool-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: multitool-b
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: multitool-a
  namespace: multitool-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multitool-a
  template:
    metadata:
      labels:
        app: multitool-a
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: multitool-b
  namespace: multitool-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multitool-b
  template:
    metadata:
      labels:
        app: multitool-b
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 80
