apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quay
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
    argocd.argoproj.io/sync-wave: "-8"
  finalizers:
    # https://argo-cd.readthedocs.io/en/latest/user-guide/app_deletion/#about-the-deletion-finalizer
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    namespace: quay
    server: {{ .Values.server }}
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: https://github.com/bpfSockOps/Quay-Entreprise-for-k8s.git
    targetRevision: master
    path: .
    helm:
      releaseName: quay
