apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: infra
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  project: infra
  destination:
    namespace: reloader
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    chart: reloader
    repoURL: https://stakater.github.io/stakater-charts
    # https://artifacthub.io/packages/helm/stakater/reloader
    targetRevision: 2.2.2
