# Spegel requires containerd
# - https://spegel.dev/docs/getting-started/#compatibility
{{ if .Values.app_spegel }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  finalizers:
    # https://argo-cd.readthedocs.io/en/latest/user-guide/app_deletion/#about-the-deletion-finalizer
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: {{ .Values.project }}
  destination:
    namespace: spegel
    server: {{ .Values.server }}
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: oci://ghcr.io/spegel-org/helm-charts/spegel
    path: .
    targetRevision: 0.3.0
{{ end }}
