apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: infra
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  project: infra
  destination:
    namespace: spegel
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    path: .
    repoURL: oci://ghcr.io/spegel-org/helm-charts/spegel
    targetRevision: 0.3.0
