apiVersion: v1
kind: Namespace
metadata:
  name: victorialogs
---
apiVersion: operator.victoriametrics.com/v1
kind: VLCluster
metadata:
  name: my-victorialogs
  namespace: victorialogs
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  vlstorage:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    image:
      # https://github.com/VictoriaMetrics/VictoriaLogs/releases
      repository: victoriametrics/victoria-logs
      tag: v1.43.1
      pullPolicy: Always
    retentionPeriod: "1y"
    replicaCount: 2
  imagePullSecrets:
    - name: my-repo-secret
  vlinsert:
    replicaCount: 2
  vlselect:
    replicaCount: 2
  requestsLoadBalancer:
    enabled: true
    spec:
      replicaCount: 2
