metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    # https://artifacthub.io/packages/helm/kyverno/kyverno
    targetRevision: 3.8.1
