spec:
  source:
    path: AppSet
    repoURL: https://github.com/kristoferlundgren/my-appset
    targetRevision: main
  sources:
    - path: Apps/AppSet/templates
      repoURL: https://github.com/kristoferlundgren/my-infra
      targetRevision: release/staging
